version: '3'

services: 

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node index.js
    networks: 
      - node-network
    tty: true
    depends_on: 
       - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql:rw
    # Comigo nao funcionou sem o user, tentei remover a imagem ou utilizar uma versao mais recente
    user: mysql
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx:
    build: 
      context: nginx
    container_name: nginx
    entrypoint: dockerize -wait http://app:3000 -timeout 50s nginx -g "daemon off;"
    networks: 
      - node-network
    ports: 
      - "8080:80"

    

networks: 
  node-network:
    driver: bridge      